### ISSUE TITLE
How to turn off the power LED on the board?

### ISSUE THREAD

**Issue by leira** [WeActStudio/WeActStudio.RP2040CoreBoard#5]
I just received a new [Piantor keyboard](https://github.com/beekeeb/piantor) which uses a WeAct RP2040 board. The only problem I have with it is the power LED on the board is always on, which is really annoying. Is there a way to turn the power LED off from QMK firmware? Thanks!

**Comment by magiczny-kacper** [comment]
@leira I think the only way is desoldering the led

**Comment by leira** [comment]
Got it. Thanks!
